AdventureWorksSales.Web/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorksSales.Web.Models
{
    public class HomeViewModel
    {
        public int TotalOrders { get; set; }
        public decimal HighestLineTotal { get; set; }

        public int FrontBrakeSalesTotal { get; set; }
    }
}

AdventureWorksSales.Web/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorksSales.Web.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages =>
            (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
    }
}

AdventureWorksSales.Web/Models/ProductCategoryViewModel.cs
using AdventureWorksSales.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorksSales.Web.Models
{
    public class ProductCategoryViewModel
    {
        public IEnumerable<ProductCategory> ProductCategories { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}

AdventureWorksSales.Web/Controllers/HomeController.cs
using AdventureWorksSales.Core.Abstract;
using AdventureWorksSales.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdventureWorksSales.Web.Controllers
{
    public class HomeController : Controller
    {
        ISalesOrderRepository _salesOrderRepo;
        public HomeController(ISalesOrderRepository salesOrderRepository)
        {
            _salesOrderRepo = salesOrderRepository;
        }
        public ActionResult Index()
        {
            var model = new HomeViewModel
            {
                TotalOrders = _salesOrderRepo.Query().Count(),
                HighestLineTotal = decimal.Round(_salesOrderRepo.GetAllLineTotal().Max(), 3, MidpointRounding.AwayFromZero),
                FrontBrakeSalesTotal =_salesOrderRepo.GetAllProductSales(948).Count()
            };

            return View(model);
        }

    }
}

AdventureWorksSales.Web/Controllers/ProductCategoryController.cs
using AdventureWorksSales.Core;
using AdventureWorksSales.Core.Abstract;
using AdventureWorksSales.Web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AdventureWorksSales.Web.Controllers
{
    public class ProductCategoryController : Controller
    {
        private IProductCategoryRepository _prodCategory;
        public int pageSize = 5;
        public ProductCategoryController(IProductCategoryRepository productCategory)
        {
            _prodCategory = productCategory;
        }
        // GET: ProductCategory
        public ActionResult Index(int page = 1)
        {
            var productCategories = _prodCategory.Query()
                .ToList();

            var prod = new ProductCategoryViewModel
            {
                ProductCategories = productCategories
                .OrderBy(p => p.ProductCategoryID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = productCategories.Count()
                },
            };

            return View(prod);
        }

        public ActionResult Create()
        {
            return View(new ProductCategory());
        }

        [HttpPost]
        public async Task<ActionResult> Create(string Name)
        {
            try
            {
                var data = new ProductCategory
                {
                    Name = Name,
                    ModifiedDate = DateTime.Now,
                    rowguid = Guid.NewGuid()
                };

                await _prodCategory.InsertAsync(data);
                TempData["message"] = string.Format("{0} has been created!", Name);

                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError($"{ex}", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                return View();
            }
            
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            ProductCategory productCategory = await _prodCategory.GetAsync(id);
            return View(productCategory);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(ProductCategory productCategory)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _prodCategory.UpdateAsync(productCategory);

                    TempData["message"] = string.Format("{0} has been updated!", productCategory.Name);

                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(productCategory);
        }

    }
}

AdventureWorksSales.Web/Views/Home/Index.cshtml
@model AdventureWorksSales.Web.Models.HomeViewModel
@{
    ViewBag.Title = "Home Page";
}

@if(Model != null) { 
    <div class="jumbotron">
    <h1>SALES ANALYSIS</h1>
    <p class="lead">This application is for test purposes and do not reflect actual data of any company or organization</p>
</div>

<div class="row">
    <div class="col-md-12">
        <h3><i>Below, sales figures are represented in US Dollars</i></h3>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Total orders</h2>
        <p class="sales">
            @Model.TotalOrders
        </p>
    </div>
    <div class="col-md-4">
        <h2>Highest line total</h2>
        <p class="sales">
            @Model.HighestLineTotal
        </p>
    </div>
    <div class="col-md-4">
        <h2>Front Brakes sales total</h2>
        <p class="sales">
            @Model.FrontBrakeSalesTotal
        </p>
    </div>
</div>
}

AdventureWorksSales.Web/Views/ProductCategory/Create.cshtml
@model AdventureWorksSales.Core.ProductCategory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.rowguid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rowguid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rowguid, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdventureWorksSales.Web/Views/ProductCategory/Edit.cshtml
@model AdventureWorksSales.Core.ProductCategory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductCategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.rowguid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.rowguid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rowguid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdventureWorksSales.Web/Views/ProductCategory/Index.cshtml
@model AdventureWorksSales.Web.Models.ProductCategoryViewModel

@{
    ViewBag.Title = "Index";
}

@if (Model.ProductCategories != null && Model.ProductCategories.Count() > 0)
{
    <div class="jumbotron">
        <h1>PRODUCT CATEGORIES</h1>
    </div>
    <div class="col-sm-12">
        <p>
            @Html.ActionLink("Add Product Category", "Create", "", new { @class = "btn btn-primary" })
        </p>
        <br />
    </div>
    if (TempData["message"] != null)
    {
        <div class="col-sm-8">
            <div class="alert alert-success">@TempData["message"]</div>
        </div>
    }
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cat in Model.ProductCategories)
            {
                <tr>
                    <td>
                        @cat.Name
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = cat.ProductCategoryID }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="pager pull-right">
        @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index",
            new { page = x }))
    </div>
}
else
{
    <div class="alert alert-warning" role="alert">
        Sorry! No records exist.
    </div>
}

AdventureWorksSales.Web/Views/Shared/_Layout.cshtml
@{ string applicationName = "Adventure Works Portal";}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @applicationName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(applicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Product Categories", "Index", "ProductCategory")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Sales Order", "Index", "SalesOrder")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @applicationName</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>